basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a GeekCoding Online Judge API server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GeekCoding API
  version: "1.0"
paths:
  /admin/category-create:
    post:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: parent_id
        in: formData
        name: parent_id
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg","","data": ""}'
          schema:
            type: string
      summary: Create Category
      tags:
      - Admin Method
  /admin/category-delete:
    delete:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: identity
        in: query
        name: identity
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200","msg","","data": ""}'
          schema:
            type: string
      summary: Delete Category
      tags:
      - Admin Method
  /admin/category-list:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      responses:
        "200":
          description: '{"code":"200","msg","","data": ""}'
          schema:
            type: string
      summary: Get Category List
      tags:
      - Admin Method
  /admin/category-update:
    put:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: parent_id
        in: formData
        name: parent_id
        type: integer
      - description: identity
        in: query
        name: identity
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200","msg","","data": ""}'
          schema:
            type: string
      summary: Update Category
      tags:
      - Admin Method
  /admin/problem-create:
    post:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: title
        in: formData
        name: title
        required: true
        type: string
      - description: content
        in: formData
        name: content
        required: true
        type: string
      - description: max_runtime
        in: formData
        name: max_runtime
        required: true
        type: integer
      - description: max_mem
        in: formData
        name: max_mem
        required: true
        type: integer
      - description: category_ids
        in: formData
        name: category_ids
        required: true
        type: string
      - description: test_cases
        in: body
        name: test_cases
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"code": 200, "data": ""}'
          schema:
            type: string
      summary: Problem Create
      tags:
      - Admin Method
  /admin/problem-update:
    put:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: identity
        in: formData
        name: identity
        required: true
        type: string
      - description: title
        in: formData
        name: title
        required: true
        type: string
      - description: content
        in: formData
        name: content
        required: true
        type: string
      - description: max_runtime
        in: formData
        name: max_runtime
        required: true
        type: integer
      - description: max_mem
        in: formData
        name: max_mem
        required: true
        type: integer
      - description: category_ids
        in: formData
        name: category_ids
        type: string
      - description: test_cases (JSON array, supports multi-line)
        in: formData
        name: test_cases
        required: true
        type: string
      responses:
        "200":
          description: '{"code": 200, "data": ""}'
          schema:
            type: string
      summary: Problem Update
      tags:
      - Admin Method
  /login:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        type: string
      - description: password
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: '{"code": 200, "data": ""}'
          schema:
            type: string
      summary: User Login
      tags:
      - Public Method
  /problem-detail:
    get:
      parameters:
      - description: problem identity
        in: query
        name: identity
        required: true
        type: string
      responses:
        "200":
          description: '{"code": 200, "data": ""}'
          schema:
            type: string
      summary: Get Problem Detail
      tags:
      - Public Method
  /problem-list:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      responses:
        "200":
          description: '{"code":"200","msg","","data": ""}'
          schema:
            type: string
      summary: Get Problem List
      tags:
      - Public Method
  /rank-list:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg","","data": ""}'
          schema:
            type: string
      summary: Get Rank List
      tags:
      - Public Method
  /register:
    post:
      parameters:
      - description: email
        in: formData
        name: email
        required: true
        type: string
      - description: code
        in: formData
        name: code
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      - description: phone
        in: formData
        name: phone
        type: string
      responses:
        "200":
          description: '{"code": 200, "data": ""}'
          schema:
            type: string
      summary: Register
      tags:
      - Public Method
  /send-code:
    post:
      parameters:
      - description: email
        in: formData
        name: email
        type: string
      responses:
        "200":
          description: '{"code": 200, "data": ""}'
          schema:
            type: string
      summary: Send Code
      tags:
      - Public Method
  /submit-list:
    get:
      parameters:
      - description: page number, default is 1
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: problem identity
        in: query
        name: problem_identity
        type: string
      - description: user identity
        in: query
        name: user_identity
        type: string
      - description: submit status
        in: query
        name: status
        type: integer
      responses:
        "200":
          description: '{"code": 200, "data": ""}'
          schema:
            type: string
      summary: Get Submit List
      tags:
      - Public Method
  /user-detail:
    get:
      parameters:
      - description: user identity
        in: query
        name: identity
        required: true
        type: string
      responses:
        "200":
          description: '{"code": 200, "data": ""}'
          schema:
            type: string
      summary: Get User Detail
      tags:
      - Public Method
  /user/submit:
    post:
      parameters:
      - description: authorization
        in: header
        name: authorization
        required: true
        type: string
      - description: problem identity
        in: query
        name: problem_identity
        required: true
        type: string
      - description: code
        in: body
        name: code
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"code": 200, "data": ""}'
          schema:
            type: string
      summary: Submit Code
      tags:
      - User Private Method
swagger: "2.0"
